#!/bin/sh

# This file is part of Superwas.
# 
# Superwas is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Superwas is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Superwas.  If not, see <http://www.gnu.org/licenses/>.
#

# Start Superwas scripting library
#
# Assumes wsadmin.sh is in the path
# 
# Author: Andre van Dijk (SuperClass IT)
# Date: $Date: 2013-01-04 16:04:36 +0100 (vr, 04 jan 2013) $
# $Id: superwas 424 2013-01-04 15:04:36Z andre $
#

SUPERWAS_HOME=`dirname $0`
# Sets TMPDIR, where the log file will be created
SUPERWAS_TMP=$HOME/log
CLASSPATH=${SUPERWAS_HOME}/lib/log4j-1.2.8.jar

wsadmin.sh \
-javaoption -DSUPERWAS_HOME=$SUPERWAS_HOME \
-javaoption -DSUPERWAS_TMP=$SUPERWAS_TMP \
-wsadmin_classpath $CLASSPATH  \
-f $SUPERWAS_HOME/superwas.py \
$*
